In [2]:
%load_ext autoreload
%autoreload 2

import numpy as np
from fatoracaoLU import solveLU

A = np.array([[2, 1, 1],
              [4, -6, 0],
              [-2, 7, 2]], dtype=float)

b = np.array([4, -2, 5], dtype=float)

x,L,U = solveLU(A, b)
print("Solução do sistema:", x)

print("Matriz L:")
for row in L:
    print(row)

print("\nMatriz U:")
for row in U:
    print(row)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Solução do sistema: [ 1.75  1.5  -1.  ]
Matriz L:
[1. 0. 0.]
[2. 1. 0.]
[-1. -1.  1.]

Matriz U:
[2. 1. 1.]
[ 0. -8. -2.]
[0. 0. 1.]
